/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root.tsx'
import { Route as EmployeesIdEditPageRouteImport } from './app/employees/$id/edit/page.tsx'
import { Route as EmployeesNewPageRouteImport } from './app/employees/new/page.tsx'
import { Route as EmployeesPageRouteImport } from './app/employees/page.tsx'
import { Route as OrganizationsIdEditPageRouteImport } from './app/organizations/$id/edit/page.tsx'
import { Route as OrganizationsIdEmployeesNewPageRouteImport } from './app/organizations/$id/employees/new/page.tsx'
import { Route as OrganizationsIdPageRouteImport } from './app/organizations/$id/page.tsx'
import { Route as OrganizationsLayoutRouteImport } from './app/organizations/layout.tsx'
import { Route as OrganizationsNewPageRouteImport } from './app/organizations/new/page.tsx'
import { Route as OrganizationsPageRouteImport } from './app/organizations/page.tsx'
import { Route as PageRouteImport } from './app/page.tsx'

const OrganizationsLayoutRoute = OrganizationsLayoutRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsPageRoute = OrganizationsPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsLayoutRoute,
} as any)
const EmployeesPageRoute = EmployeesPageRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewPageRoute = OrganizationsNewPageRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => OrganizationsLayoutRoute,
} as any)
const OrganizationsIdPageRoute = OrganizationsIdPageRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => OrganizationsLayoutRoute,
} as any)
const EmployeesNewPageRoute = EmployeesNewPageRouteImport.update({
  id: '/employees/new/',
  path: '/employees/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdEditPageRoute = OrganizationsIdEditPageRouteImport.update({
  id: '/$id/edit/',
  path: '/$id/edit/',
  getParentRoute: () => OrganizationsLayoutRoute,
} as any)
const EmployeesIdEditPageRoute = EmployeesIdEditPageRouteImport.update({
  id: '/employees/$id/edit/',
  path: '/employees/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdEmployeesNewPageRoute =
  OrganizationsIdEmployeesNewPageRouteImport.update({
    id: '/$id/employees/new/',
    path: '/$id/employees/new/',
    getParentRoute: () => OrganizationsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/organizations': typeof OrganizationsLayoutRouteWithChildren
  '/employees': typeof EmployeesPageRoute
  '/organizations/': typeof OrganizationsPageRoute
  '/employees/new': typeof EmployeesNewPageRoute
  '/organizations/$id': typeof OrganizationsIdPageRoute
  '/organizations/new': typeof OrganizationsNewPageRoute
  '/employees/$id/edit': typeof EmployeesIdEditPageRoute
  '/organizations/$id/edit': typeof OrganizationsIdEditPageRoute
  '/organizations/$id/employees/new': typeof OrganizationsIdEmployeesNewPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/employees': typeof EmployeesPageRoute
  '/organizations': typeof OrganizationsPageRoute
  '/employees/new': typeof EmployeesNewPageRoute
  '/organizations/$id': typeof OrganizationsIdPageRoute
  '/organizations/new': typeof OrganizationsNewPageRoute
  '/employees/$id/edit': typeof EmployeesIdEditPageRoute
  '/organizations/$id/edit': typeof OrganizationsIdEditPageRoute
  '/organizations/$id/employees/new': typeof OrganizationsIdEmployeesNewPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/organizations': typeof OrganizationsLayoutRouteWithChildren
  '/employees/': typeof EmployeesPageRoute
  '/organizations/': typeof OrganizationsPageRoute
  '/employees/new/': typeof EmployeesNewPageRoute
  '/organizations/$id/': typeof OrganizationsIdPageRoute
  '/organizations/new/': typeof OrganizationsNewPageRoute
  '/employees/$id/edit/': typeof EmployeesIdEditPageRoute
  '/organizations/$id/edit/': typeof OrganizationsIdEditPageRoute
  '/organizations/$id/employees/new/': typeof OrganizationsIdEmployeesNewPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations'
    | '/employees'
    | '/organizations/'
    | '/employees/new'
    | '/organizations/$id'
    | '/organizations/new'
    | '/employees/$id/edit'
    | '/organizations/$id/edit'
    | '/organizations/$id/employees/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/organizations'
    | '/employees/new'
    | '/organizations/$id'
    | '/organizations/new'
    | '/employees/$id/edit'
    | '/organizations/$id/edit'
    | '/organizations/$id/employees/new'
  id:
    | '__root__'
    | '/'
    | '/organizations'
    | '/employees/'
    | '/organizations/'
    | '/employees/new/'
    | '/organizations/$id/'
    | '/organizations/new/'
    | '/employees/$id/edit/'
    | '/organizations/$id/edit/'
    | '/organizations/$id/employees/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  OrganizationsLayoutRoute: typeof OrganizationsLayoutRouteWithChildren
  EmployeesPageRoute: typeof EmployeesPageRoute
  EmployeesNewPageRoute: typeof EmployeesNewPageRoute
  EmployeesIdEditPageRoute: typeof EmployeesIdEditPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsPageRouteImport
      parentRoute: typeof OrganizationsLayoutRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new/': {
      id: '/organizations/new/'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewPageRouteImport
      parentRoute: typeof OrganizationsLayoutRoute
    }
    '/organizations/$id/': {
      id: '/organizations/$id/'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdPageRouteImport
      parentRoute: typeof OrganizationsLayoutRoute
    }
    '/employees/new/': {
      id: '/employees/new/'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id/edit/': {
      id: '/organizations/$id/edit/'
      path: '/$id/edit'
      fullPath: '/organizations/$id/edit'
      preLoaderRoute: typeof OrganizationsIdEditPageRouteImport
      parentRoute: typeof OrganizationsLayoutRoute
    }
    '/employees/$id/edit/': {
      id: '/employees/$id/edit/'
      path: '/employees/$id/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof EmployeesIdEditPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id/employees/new/': {
      id: '/organizations/$id/employees/new/'
      path: '/$id/employees/new'
      fullPath: '/organizations/$id/employees/new'
      preLoaderRoute: typeof OrganizationsIdEmployeesNewPageRouteImport
      parentRoute: typeof OrganizationsLayoutRoute
    }
  }
}

interface OrganizationsLayoutRouteChildren {
  OrganizationsPageRoute: typeof OrganizationsPageRoute
  OrganizationsIdPageRoute: typeof OrganizationsIdPageRoute
  OrganizationsNewPageRoute: typeof OrganizationsNewPageRoute
  OrganizationsIdEditPageRoute: typeof OrganizationsIdEditPageRoute
  OrganizationsIdEmployeesNewPageRoute: typeof OrganizationsIdEmployeesNewPageRoute
}

const OrganizationsLayoutRouteChildren: OrganizationsLayoutRouteChildren = {
  OrganizationsPageRoute: OrganizationsPageRoute,
  OrganizationsIdPageRoute: OrganizationsIdPageRoute,
  OrganizationsNewPageRoute: OrganizationsNewPageRoute,
  OrganizationsIdEditPageRoute: OrganizationsIdEditPageRoute,
  OrganizationsIdEmployeesNewPageRoute: OrganizationsIdEmployeesNewPageRoute,
}

const OrganizationsLayoutRouteWithChildren =
  OrganizationsLayoutRoute._addFileChildren(OrganizationsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  OrganizationsLayoutRoute: OrganizationsLayoutRouteWithChildren,
  EmployeesPageRoute: EmployeesPageRoute,
  EmployeesNewPageRoute: EmployeesNewPageRoute,
  EmployeesIdEditPageRoute: EmployeesIdEditPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from '@tanstack/react-start'
import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
