/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as OrganizationsNewIndexRouteImport } from './routes/organizations/new/index'
import { Route as OrganizationsIdIndexRouteImport } from './routes/organizations/$id/index'
import { Route as EmployeesNewIndexRouteImport } from './routes/employees/new/index'
import { Route as OrganizationsIdEditIndexRouteImport } from './routes/organizations/$id/edit/index'
import { Route as EmployeesIdEditIndexRouteImport } from './routes/employees/$id/edit/index'
import { Route as OrganizationsIdEmployeesNewIndexRouteImport } from './routes/organizations/$id/employees/new/index'

const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewIndexRoute = OrganizationsNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const OrganizationsIdIndexRoute = OrganizationsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const EmployeesNewIndexRoute = EmployeesNewIndexRouteImport.update({
  id: '/employees/new/',
  path: '/employees/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdEditIndexRoute =
  OrganizationsIdEditIndexRouteImport.update({
    id: '/$id/edit/',
    path: '/$id/edit/',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const EmployeesIdEditIndexRoute = EmployeesIdEditIndexRouteImport.update({
  id: '/employees/$id/edit/',
  path: '/employees/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdEmployeesNewIndexRoute =
  OrganizationsIdEmployeesNewIndexRouteImport.update({
    id: '/$id/employees/new/',
    path: '/$id/employees/new/',
    getParentRoute: () => OrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/employees': typeof EmployeesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/employees/new': typeof EmployeesNewIndexRoute
  '/organizations/$id': typeof OrganizationsIdIndexRoute
  '/organizations/new': typeof OrganizationsNewIndexRoute
  '/employees/$id/edit': typeof EmployeesIdEditIndexRoute
  '/organizations/$id/edit': typeof OrganizationsIdEditIndexRoute
  '/organizations/$id/employees/new': typeof OrganizationsIdEmployeesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/employees/new': typeof EmployeesNewIndexRoute
  '/organizations/$id': typeof OrganizationsIdIndexRoute
  '/organizations/new': typeof OrganizationsNewIndexRoute
  '/employees/$id/edit': typeof EmployeesIdEditIndexRoute
  '/organizations/$id/edit': typeof OrganizationsIdEditIndexRoute
  '/organizations/$id/employees/new': typeof OrganizationsIdEmployeesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/employees/': typeof EmployeesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/employees/new/': typeof EmployeesNewIndexRoute
  '/organizations/$id/': typeof OrganizationsIdIndexRoute
  '/organizations/new/': typeof OrganizationsNewIndexRoute
  '/employees/$id/edit/': typeof EmployeesIdEditIndexRoute
  '/organizations/$id/edit/': typeof OrganizationsIdEditIndexRoute
  '/organizations/$id/employees/new/': typeof OrganizationsIdEmployeesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations'
    | '/employees'
    | '/organizations/'
    | '/employees/new'
    | '/organizations/$id'
    | '/organizations/new'
    | '/employees/$id/edit'
    | '/organizations/$id/edit'
    | '/organizations/$id/employees/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/organizations'
    | '/employees/new'
    | '/organizations/$id'
    | '/organizations/new'
    | '/employees/$id/edit'
    | '/organizations/$id/edit'
    | '/organizations/$id/employees/new'
  id:
    | '__root__'
    | '/'
    | '/organizations'
    | '/employees/'
    | '/organizations/'
    | '/employees/new/'
    | '/organizations/$id/'
    | '/organizations/new/'
    | '/employees/$id/edit/'
    | '/organizations/$id/edit/'
    | '/organizations/$id/employees/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  EmployeesNewIndexRoute: typeof EmployeesNewIndexRoute
  EmployeesIdEditIndexRoute: typeof EmployeesIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new/': {
      id: '/organizations/new/'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/$id/': {
      id: '/organizations/$id/'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/employees/new/': {
      id: '/employees/new/'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id/edit/': {
      id: '/organizations/$id/edit/'
      path: '/$id/edit'
      fullPath: '/organizations/$id/edit'
      preLoaderRoute: typeof OrganizationsIdEditIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/employees/$id/edit/': {
      id: '/employees/$id/edit/'
      path: '/employees/$id/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof EmployeesIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id/employees/new/': {
      id: '/organizations/$id/employees/new/'
      path: '/$id/employees/new'
      fullPath: '/organizations/$id/employees/new'
      preLoaderRoute: typeof OrganizationsIdEmployeesNewIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  OrganizationsIdIndexRoute: typeof OrganizationsIdIndexRoute
  OrganizationsNewIndexRoute: typeof OrganizationsNewIndexRoute
  OrganizationsIdEditIndexRoute: typeof OrganizationsIdEditIndexRoute
  OrganizationsIdEmployeesNewIndexRoute: typeof OrganizationsIdEmployeesNewIndexRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  OrganizationsIdIndexRoute: OrganizationsIdIndexRoute,
  OrganizationsNewIndexRoute: OrganizationsNewIndexRoute,
  OrganizationsIdEditIndexRoute: OrganizationsIdEditIndexRoute,
  OrganizationsIdEmployeesNewIndexRoute: OrganizationsIdEmployeesNewIndexRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  EmployeesIndexRoute: EmployeesIndexRoute,
  EmployeesNewIndexRoute: EmployeesNewIndexRoute,
  EmployeesIdEditIndexRoute: EmployeesIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
